package org.csc133.a1;

import static com.codename1.ui.CN.*;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

import java.awt.event.ActionListener;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class AppMain extends Lifecycle {
    @Override
    public void runApp() {
        new Game();
    }
}

class Game extends Form implements Runnable{
    GameWorld gw;
    public Game(){
        gw = new GameWorld();
        //addKeyListener(-93,(evt) -> );
        //addKeyListener(-94,(evt) -> );
        //addKeyListener(-91,(evt) -> );
        //addKeyListener(-92,(evt) -> );
        //addKeyListener('f',(evt) -> );
        //addKeyListener('d',(evt) -> );
        addKeyListener('Q',(evt) -> gw.quit());
    }
    //public void addKeyListener(int KeyCode, ActionListener listener){}
    @Override
    public void run() {

    }
    public void paint (Graphics g){
        super.paint(g);
        gw.draw(g);
    }
}
class GameWorld{
    public GameWorld(){
        init();
    }
    private void init(){

    }
    public void quit(){
        Display.getInstance().exitApplication();
    }
    void draw(Graphics g){

    }
}
class River{
    public River(){

    }
    private void init(){

    }
    void draw(Graphics g){

    }
}
class Helipad{
    public Helipad(){

    }
    private void init(){

    }
    void draw(Graphics g){

    }
}
class River{
    public River(){

    }
    private void init(){

    }
    void draw(Graphics g){

    }
}
class Fire{
    public Fire(){

    }
    private void init(){

    }
    void draw(Graphics g){

    }
}
class Helicopter{
    public Helicopter(){

    }
    private void init(){

    }
    void draw(Graphics g){

    }
}